<?php

namespace mod_ctsr;

use core\form\persistent;

class ctsr_form extends persistent
{
    /** @var string Persistent class name. */
    protected static $persistentclass = 'mod_ctsr\\ctsr_user';

    /** @var array Fields to remove when getting the final data.
     * Note: not adding 'userid' results in the error "Unexpected property 'userid' requested."
     * This is because it doesn't exist as a field in the persistent.
     */
    protected static $fieldstoremove = ['submitbutton', 'userid', 'updatectsr'];

    /**
     * @inheritDoc
     */
    protected function definition()
    {
        $mform = $this->_form;

        // User ID
        $mform->addElement('hidden', 'user_id');
        $mform->setType('user_id', PARAM_INT);
        $mform->setConstant('user_id', $this->_customdata['user_id']);

        $mform->addElement('hidden', 'ctsr_id');
        $mform->setType('ctsr_id', PARAM_INT);
        $mform->setConstant('ctsr_id', $this->_customdata['ctsr_id']);

        $mform->addElement('select', 'item_01_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_01_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_01_comments', 'Comments:');
        $mform->setType('item_01_comments', PARAM_RAW);

        $mform->addElement('select', 'item_02_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_02_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_02_comments', 'Comments:');
        $mform->setType('item_02_comments', PARAM_RAW);

        $mform->addElement('select', 'item_03_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_03_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_03_comments', 'Comments:');
        $mform->setType('item_03_comments', PARAM_RAW);

        $mform->addElement('select', 'item_04_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_04_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_04_comments', 'Comments:');
        $mform->setType('item_04_comments', PARAM_RAW);

        $mform->addElement('select', 'item_05_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_05_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_05_comments', 'Comments:');
        $mform->setType('item_05_comments', PARAM_RAW);

        $mform->addElement('select', 'item_06_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_06_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_06_comments', 'Comments:');
        $mform->setType('item_06_comments', PARAM_RAW);

        $mform->addElement('select', 'item_07_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_07_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_07_comments', 'Comments:');
        $mform->setType('item_07_comments', PARAM_RAW);

        $mform->addElement('select', 'item_08_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_08_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_08_comments', 'Comments:');
        $mform->setType('item_08_comments', PARAM_RAW);

        $mform->addElement('select', 'item_09_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_09_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_09_comments', 'Comments:');
        $mform->setType('item_09_comments', PARAM_RAW);

        $mform->addElement('select', 'item_10_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_10_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_10_comments', 'Comments:');
        $mform->setType('item_10_comments', PARAM_RAW);

        $mform->addElement('select', 'item_11_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_11_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_11_comments', 'Comments:');
        $mform->setType('item_11_comments', PARAM_RAW);

        $mform->addElement('select', 'item_12_score', 'Score:', $this->make_scoring_select_items());
        $mform->setType('item_12_score', PARAM_TEXT);
        $mform->addElement('editor', 'item_12_comments', 'Comments:');
        $mform->setType('item_12_comments', PARAM_RAW);

        $mform->addElement('submit', 'updatectsr', 'Save progress');
        $mform->registerNoSubmitButton('updatectsr');

        $mform->addElement('submit', 'submitbutton', 'Submit');
    }

    private function make_scoring_select_items()
    {
        $scores = ['0', '0.5', '1.0', '1.5', '2.0', '2.5', '3.0', '3.5', '4.0', '4.5', '5.0', '5.5', '6.0'];
        return array_combine($scores, $scores);
    }

    public function definition_after_data()
    {
        $data = $this->get_data();

        parent::definition_after_data(); // TODO: Change the autogenerated stub
    }

    /**
     * This is overwritten because we are updating the DB record on Update (which is a 'nosubmitbutton'),
     * and therefore we need to validate the fields (pass 'true').
     *
     * @return bool|null
     */
    public function is_validated()
    {
        if (!$this->_definition_finalized) {
            $this->_definition_finalized = true;
            $this->definition_after_data();
        }
        return $this->validate_defined_fields(true);
    }
}